### ISSUE TITLE
Validação do tamanho mínimo de telefone

### ISSUE THREAD

**Issue by andersonbispo** [smartlaudos/diagnes#46]
Há uma validação nos campos de telefone que só deixa salvar se o usuário digitar no mínimo 8 digitos. Acontece que ele sempre precisa digitar o código da área. Então é possível salvar um número de telefone nesse formato: (81) 9999-89. Formato este que não é um número de telefone válido. Deveríamos mudar essa validação para no mínimo 10 dígitos.

**Comment by valdenia** [comment]
Bug corrigido e validado em 18/04/15.
